# Page settings
baseurl = "https://pixiesfaces.netlify.com"
title = "Pixies Face Painting"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Jenny Saunders"
  description = "Beautiful Face Painting"
  email = "info@pixiesfaces.com"
  github = "https://github.com/pixiesfaces"
  facebook = "https://facebook.com/pixiesfaces"
  seoimage = "/images/logo.png"
  twitter = "@pixiesfaces"
  site_type = "LocalBusiness"
  local_business_type = "EntertainmentBusiness"

  # Main Colours
  whiteColor = "#fff"
  backgroundColor = "#fff"
  textColor = "#3d2b3d"
  highlightColor = "#f0f"
 
  # Gradient Home/Hero Section
  homeColor1 = "#f00"
  homeColor2 = "#f0f"

  # Gradient work/Gallery Section
  workColor1 = "#f0f"
  workColor2 = "#00f"

  # Gradient services/Bookings Section
  servicesColor1 = "#00f"
  servicesColor2 = "#0f0"

  # Default body ext size
  bodyTextSize = "18px"
  
  # Brand in top left of menu bar text size
  brandTextSize = "30px"

  # Menu item Text size
  menuTextSize = "18px"
 
  # Hero image overlay main text size
  heroTextSizeH1 = "50px"

  # Hero image overlay sub text size
  heroTextSizeH2 = "28px"

  # Intro section icon size
  introIconSize = "50px"

  # Intro section heading text size
  introTextSizeH2 = "24px"

  # Intro section text size
  introTextSize = "16px"

  # All section headings text size
  sectionHeadingTextSizeH2 = "50px"

  # All section headings text size - mobile
  sectionHeadingTextSizeH2Mobile = "30px"

  # All section sub headings text size
  sectionHeadingTextSizeH3 = "28px"
  
  # All section sub headings text size - mobile
  sectionHeadingTextSizeH3Mobile = "24px"

  # Gallery title text size
  workItemTextSizeH2 = "18px"

  # Gallery - not used
  workItemTextSizeSpan = "16px"

  # Testimonal text sixe
  testimonialTextSize = "18px"
  
  # Testimonal author text sixe  
  testimonialAuthorTextSize = "16px"

  # Testimonal - not used
  testimonialSubTextSize = "16px"

  # Services icon size
  servicesIconSize = "70px"

  # Services heading text size
  servicesTextSizeH3 = "24px"

  # Services description text size
  servicesTextSize = "18px"

  # Contact form text size
  formTextSize = "18px"

  # go to top button icon size
  goTopIconSize = "40px"

  # Social icons size
  socialIconSize = "16px"

  # Copyright text size (footer and gallery)
  copyrightTextSize = "14px"

  # Error text size
  pixiesErrorTextSizeH1 = "50px"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  # Navigation
  [params.navigation]
    showlogo = true
    img = "logo.png"
    logoheight = "55px"
    logowidth = "55px"
    alt = "Pixies Logo"

    # Menu Configuration
    home = "Home"
    work = "Gallery"
    testimonials = "Testimonials"
    services = "Booking Info"
    contact = "Contact Us"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Fixed Background section
  [params.background]
    enableheader = true  
    enablefooter = true  
    image = "logo.png"
    alt = "Pixies Logo"

  # Hero section
  [params.hero]
    title = "Pixies Face Painting"
    subtitle = 'Beautiful Face Painting'
    background = "full_image_1.jpg"
    alt = "Pixies Logo"

  # Intro section
  # Font awesome icons https://fontawesome.com/icons
  [params.intro]

  [[params.intro.item]]
    title = "Face Painting"
    description = "Your childern will go mad for these faces!"
    navigation = "testimonials"
    button = "What People Say"
    icon = "fa-solid fa-paintbrush"
    img = "snowtiger.png"
    alt = "Alt Text"

  [[params.intro.item]]
    title = "Balloons"
    description = "Amazing balloons, the like of which you've never seen."
    navigation = "work"
    button = "See For Yourself"
    icon = "fa-solid fa-paintbrush"
    img = "iceprincess.png"
    alt = "Alt Text"

  [[params.intro.item]]
    title = "Fairy Parties"
    description = "You won't believe how fun Pixies parties can be!"
    navigation = "services"
    button = "Booking Info"
    icon = "fa-solid fa-paintbrush"
    img = "flowers.png"
    alt = "Alt Text"

  # Work section
  [params.work]
    enable = true
    title = "Gallery"
    description = "Have a look at some of Pixie's amazing faces."
    footertext = '&copy; Pixies Face Painting 2022'

    [[params.work.row]]
      img = "snowtiger.png"
      alt = "Snow Tiger"
      title = "Snow Tiger"

    [[params.work.row]]
      img = "iceprincess.png"
      alt = "Ice Princess"
      title = "Ice Princess"

    [[params.work.row]]
      img = "irridescentbutterfly.png"
      alt = "Irridescent Butterfly"
      title = "Irridescent Butterfly"

    [[params.work.row]]
      img = "snowtiger.png"
      alt = "Snow Tiger"
      title = "Snow Tiger"

    [[params.work.row]]
      img = "iceprincess.png"
      alt = "Ice Princess"
      title = "Ice Princess"

    [[params.work.row]]
      img = "irridescentbutterfly.png"
      alt = "Irridescent Butterfly"
      title = "Irridescent Butterfly"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "People love Pixie!"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"
    
  # Services section
  [params.services]
    enable = true
    title = "Booking Info"
    description = "What value for money!"

    [[params.services.item]]
      title = "Face Painting"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-paintbrush"

    [[params.services.item]]
      title = "Ballooning"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-paintbrush"

    [[params.services.item]]
      title = "Fairy Parties"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-paintbrush"

  # Contact section
  [params.contact]
    enable = true
    form = true
    title = "Get in touch"
    description = "We'd love to hear from you."
    info = "Contact details"
    
    # Font awesome icons https://fontawesome.com/icons
    details = [
        ["fa-solid fa-phone", "tel:+61406074909", "0406 074 909"],
        ["fa-brands fa-facebook-messenger", "https://m.me/pixiesfaces", "Messenger"],
      ]
    
    # Form Labels
    email = "Your Email"
    phone = "Your Contact Number"
    message = "Message"
    button = "Send message"

  # Footer section
  # Font awesome icons https://fontawesome.com/icons
  [params.footer]
    enable = true
    copyright = '&copy; Pixies Face Painting 2022'
    links = [
        ["fa-brands fa-instagram", "https://instagram.com/pixiesfaces"],
        ["fa-brands fa-facebook-f", "https://facebook.com/pixiesfaces"],
        ["fa-brands fa-twitter", "https://twitter.com/pixiesfaces"]
      ]

  [params.errorpage]
    image = "logo.png"
    alt = "Pixies Logo"
    heading = "That page doesn't exist"
    details = "Back to Home"
    

