# Page settings
baseurl = "https://pixiesfaces.netlify.com"
title = "Pixies Face Painting"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableRobotsTXT = true
canonifyURLs = true

[params]
  # SEO Related Config
  author = "Jenny Saunders"
  description = "Beautiful Face Painting"
  email = "info@pixiesfaces.com"
  github = "https://github.com/pixiesfaces"
  facebook = "https://facebook.com/pixiesfaces"
  seoimage = "/images/background-logo.png"
  twitter = "@pixiesfaces"
  site_type = "LocalBusiness"
  local_business_type = "EntertainmentBusiness"
  favicon = "favicon.png"

  # Main Colours
  backgroundColor = "#fff"
  whiteColor = "#fff"
  textColor = "#3d2b3d"
  highlightColor = "#9900f6" 

  # Nav Toggle
  navbarHeight = "50px"
  navbarToggleTopPadding = "8px"
  navToggleColor = "#3d2b3d"
  barThickness = "4px"
  burgerWidth = "40px"
  spacing = "-12px"
  spacingActive = "-15px"

  # Gradient Home/Hero Section
  homeColor1 = "#f00"
  homeColor2 = "#f0f"

  # Gradient work/Gallery Section
  workColor1 = "#f0f"
  workColor2 = "#00f"

  # Gradient testimonial Section
  testimonialColor1 = "#00f"
  testimonialColor2 = "#f0f"

  # Gradient services/Bookings Section
  servicesColor1 = "#00f"
  servicesColor2 = "#0f0"

  # Default body text size
  bodyTextSize = "18px"
  
  # Menu item Text size
  menuTextSize = "22px"
  toggleMenuTextSize = "22px"
 
  # Background Header Section
  # icon size should be about 2/3 of button size
  # offset should be negative half button size
  gotoSectionIconSize = "33px"
  gotoSectionButtonSize = "50px"
  gotoSectionButtonOffset = "-25px"
  gotoSectionIconColour = "#3d2b3d"

  # Hero image text sizes
  heroTextSizeH1 = "50px"
  heroTextSizeH2 = "28px"

  # Intro section text sizes
  introIconSize = "50px"
  introTextSizeH2 = "24px"
  introTextSize = "16px"

  # General section headings text sizes
  sectionHeadingTextSizeH2 = "50px"
  sectionHeadingTextSizeH2Mobile = "30px"
  sectionHeadingTextSizeH3 = "28px"
  sectionHeadingTextSizeH3Mobile = "24px"

  # Gallery section text sizes
  workItemTextSizeH2 = "18px"
  # Gallery - not used
  workItemTextSizeSpan = "16px"

  # Testimonal section text sizes
  testimonialIconSize = "50px"
  testimonialTextSize = "18px"
  testimonialAuthorTextSize = "16px"

  # Services section text sizes
  servicesIconSize = "70px"
  servicesTextSizeH3 = "24px"
  servicesTextSize = "18px"

  # Contact section text sizes
  formTextSize = "18px"

  # Footer text sizes
  goTopIconSize = "40px"
  socialIconSize = "16px"
  copyrightTextSize = "14px"

  # Error text sizes
  pixiesErrorTextSizeH1 = "50px"
  pixiesErrorTextSizeH2 = "28px"

  # Gradient Home/Hero Section
  errorColor1 = "#f00"
  errorColor2 = "#f0f"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  # Navigation
  [params.navigation]
    showlogo = true
    img = "banner-logo.png"
    logoheight = "50px"
    logowidth = "50px"
    alt = "Pixies Logo"

    # Menu Configuration
    home = "Intro"
    work = "Gallery"
    testimonials = "Testimonials"
    services = "Booking Info"
    contact = "Contact Us"

  [params.navigation.social]
    enable = true
    links = [
        ["fa-brands fa-instagram", "https://instagram.com/pixiesfacepainting"],
        ["fa-brands fa-facebook-f", "https://facebook.com/pixiesfaces"]
      ]

  # Fixed Background section
  [params.background]
    enableheader = true  
    enablefooter = true  
    image = "background-logo.png"
    alt = "Pixies Logo"

  # Hero section
  [params.hero]
    title = "Pixies Face Painting"
    subtitle = 'Beautiful Face Painting'
    image = "redtiger.png"
    alt = "Pixies Logo"

  # Intro section
  # Font awesome icons https://fontawesome.com/icons
  [params.intro]

  [[params.intro.item]]
    title = "Face Painting"
    description = "Your childern will go mad for these faces!"
    navigation = "testimonials"
    button = "What People Say"
    icon = "fa-solid fa-comments"
    img = "snowtiger.png"
    alt = "Alt Text"

  [[params.intro.item]]
    title = "Balloons"
    description = "Amazing balloons, the like of which you've never seen."
    navigation = "work"
    button = "See For Yourself"
    icon = "fa-solid fa-images"
    img = "iceprincess.png"
    alt = "Alt Text"

  [[params.intro.item]]
    title = "Fairy Parties"
    description = "You won't believe how fun Pixies parties can be!"
    navigation = "services"
    button = "Booking Info"
    icon = "fa-solid fa-face-smile-beam"
    img = "flowers.png"
    alt = "Alt Text"

  # Work section
  [params.work]
    enable = true
    title = "Gallery"
    description = "Have a look at some of Pixie's amazing faces."
    footertext = '&copy; Pixies Face Painting 2022'

    [[params.work.row]]
      img = "iceprincess.png"
      alt = "Ice Princess"
      title = "Ice Princess"

    [[params.work.row]]
      img = "irridescentbutterfly.png"
      alt = "Irridescent Butterfly"
      title = "Irridescent Butterfly"

    [[params.work.row]]
      img = "redtiger.png"
      alt = "Red Tiger"
      title = "Red Tiger"

    [[params.work.row]]
      img = "snaketiger.png"
      alt = "Snake Tiger"
      title = "Snake Tiger"

   [[params.work.row]]
      img = "flowerprincess.png"
      alt = "Flower Princess"
      title = "Flower Princess"

   [[params.work.row]]
      img = "flowers.png"
      alt = "Flowers"
      title = "Flowers"

   [[params.work.row]]
      img = "happydog.png"
      alt = "Happy Dog"
      title = "Happy Dog"

    [[params.work.row]]
      img = "snowtiger.png"
      alt = "Snow Tiger"
      title = "Snow Tiger"

    [[params.work.row]]
      img = "illusion.png"
      alt = "Illusion Magazine"
      title = "Illusion Magazine"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "People love Pixie!"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Sarah McDermott'
      icon = "fa-solid fa-user"

    [[params.testimonials.item]]
      quote = "&ldquo;Pixie is amazing.  She made my daughter's day so special!&rdquo;"
      person = 'Mary Smith'
      icon = "fa-solid fa-user"

    [[params.testimonials.item]]
      quote = "&ldquo;Always a professional, we hire Pixie every year!&rdquo;"
      person = 'Bob Harris'
      icon = "fa-regular fa-user"
    
  # Services section
  [params.services]
    enable = true
    title = "Booking Info"
    description = "What value for money!"

    [[params.services.item]]
      title = "Face Painting"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-paintbrush"

    [[params.services.item]]
      title = "Ballooning"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-face-smile"

    [[params.services.item]]
      title = "Fairy Parties"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-cake-candles"

  # Contact section
  [params.contact]
    enable = true
    form = true
    title = "Get in touch"
    description = "We'd love to hear from you."
    info = "Contact details"
    
    # Font awesome icons https://fontawesome.com/icons
    details = [
        ["fa-solid fa-phone", "tel:+61406074909", "0406 074 909"],
        ["fa-brands fa-facebook-messenger", "https://m.me/pixiesfaces", "Messenger"],
      ]
    
    # Form Labels
    email = "Your Email"
    phone = "Your Contact Number"
    message = "Message"
    button = "Send message"

  # Footer section
  # Font awesome icons https://fontawesome.com/icons
  [params.footer]
    enable = true
    copyright = '&copy; Pixies Face Painting 2022'
    links = [
        ["fa-brands fa-instagram", "https://instagram.com/pixiesfacepainting"],
        ["fa-brands fa-facebook-f", "https://facebook.com/pixiesfaces"]
      ]

  [params.errorpage]
    image = "redtiger.png"
    alt = "Red Tiger"
    title = "Sorry"
    subtitle = "It seems that page does not exist"
    button = "Back to Home"