# Page settings
baseurl = "http://pixiesfaces.netlify.com"
title = "Pixies Face Painting"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableRobotsTXT = true
canonifyURLs = true

[params]
  author = "Jenny Saunders"
  description = "Beautiful Face Painting"
  email = "info@pixiesfaces.com"
  github = "https://github.com/pixiesfaces"
  facebook = "https://facebook.com/pixiesfaces"
  seoimage = "/images/logo.png"
  twitter = "@pixiesfaces"
  site_type = "LocalBusiness"
  local_business_type = "EntertainmentBusiness"

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

  # Navigation
  [params.navigation]
    showbrand = false
    brand = "Pixies"
    showlogo = true
    img = "logo.png"
    logoheight = "50px"
    logowidth = "50px"
    alt = "Pixies Logo"

    # Menu Configuration
    logo = "Home"
    home = "Intro"
    work = "Gallery"
    testimonials = "Testimonials"
    services = "Booking Info"
    contact = "Contact Us"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Logo section
  [params.logo]
    enable = true  
    background = "logo.png"
    alt = "Alt Text"

  # Hero section
  [params.hero]
    title = "Pixies Face Painting"
    subtitle = 'Beautiful Face Painting'
    background = "full_image_1.jpg"
    alt = "Pixies Logo"

  # Intro section
  # Font awesome icons https://fontawesome.com/icons
  [params.intro]

  [[params.intro.item]]
    title = "Face Painting"
    description = "Your childern will go mad for these faces!"
    navigation = "contact"
    button = "Face Painting"
    icon = "fa-solid fa-paintbrush"
    img = "snowtiger.png"
    alt = "Alt Text"


  [[params.intro.item]]
    title = "Balloons"
    description = "Amazing balloons, the like of which you've never seen."
    navigation = "contact"
    button = "Balloons"
    icon = "fa-solid fa-balloons"
    img = "iceprincess.png"
    alt = "Alt Text"

  [[params.intro.item]]
    title = "Fairy Parties"
    description = "You won't believe how fun Pixies parties can be!"
    navigation = "services"
    button = "Fairy Parties"
    icon = "fa-solid fa-paintbrush"
    img = "flowers.png"
    alt = "Alt Text"

  # Work section
  [params.work]
    enable = true
    title = "Gallery"
    description = "Have a look at some of Pixie's amazing faces."
    footertext = '&copy; Pixies Face Painting 2022'

    [[params.work.row]]
      img = "snowtiger.png"
      alt = "Snow Tiger"
      title = "Snow Tiger"

    [[params.work.row]]
      img = "iceprincess.png"
      alt = "Ice Princess"
      title = "Ice Princess"

    [[params.work.row]]
      img = "irridescentbutterfly.png"
      alt = "Irridescent Butterfly"
      title = "Irridescent Butterfly"

    [[params.work.row]]
      img = "snowtiger.png"
      alt = "Snow Tiger"
      title = "Snow Tiger"

    [[params.work.row]]
      img = "iceprincess.png"
      alt = "Ice Princess"
      title = "Ice Princess"

    [[params.work.row]]
      img = "irridescentbutterfly.png"
      alt = "Irridescent Butterfly"
      title = "Irridescent Butterfly"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "People love Pixie!"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"
    
  # Services section
  [params.services]
    enable = true
    title = "Booking Info"
    description = "What value for money!"

    [[params.services.item]]
      title = "Face Painting"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-paintbrush"

    [[params.services.item]]
      title = "Ballooning"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-paintbrush"

    [[params.services.item]]
      title = "Fairy Parties"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "fa-solid fa-paintbrush"

  # Contact section
  [params.contact]
    enable = true
    form = true
    title = "Get in touch"
    description = "Call or send me a message"
    
    # Font awesome icons https://fontawesome.com/icons
    details = [
        ["fa-solid fa-phone", "+61 406 074 909"],
        ["fa-brands fa-facebook-messenger", "https://m.me/pixiesfaces"],
        ["fa-solid fa-house", "7 Vista Avenue, Ringwood East, Victoria 3135, Australia"],
      ]

    email = "Your Email"
    phone = "Your Contact Number"
    message = "Message"
    button = "Send message"

  # Footer section
  # Font awesome icons https://fontawesome.com/icons
  [params.footer]
    enable = true
    copyright = '&copy; Pixies Face Painting 2022'
    links = [
        ["fa-brands fa-instagram", "https://instagram.com/pixiesfaces"],
        ["fa-brands fa-facebook-f", "https://facebook.com/pixiesfaces"],
        ["fa-brands fa-twitter", "https://twitter.com/pixiesfaces"]
      ]
