# Page settings
baseurl = "/"
title = "Pixies Face Painting"
languageCode = "en-us"

[params]

  # Meta
  author = "Jenny Saunders"
  description = "Beautiful Face Painting"
  email = "info@pixiesfaces.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    showbrand = true
    brand = "Pixies"
    logo = "Home"
    home = "Intro"
    work = "Gallery"
    testimonials = "Testimonials"
    services = "Booking Info"
    contact = "Contact Us"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Logo section
  [params.logo]
    enable = true  
    background = "logo.png"

  # Hero section
  [params.hero]
    title = "Pixies Face Painting"
    subtitle = 'Beautiful Face Painting'
    background = "full_image_1.jpg"
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Face Painting"
    description = "Your childern will go mad for these faces!"
    navigation = "contact"
    button = "Face Painting"
    icon = "icon-bulb"
    img = "snowtiger.png"

  [[params.intro.item]]
    title = "Balloons"
    description = "Amazing balloons, the like of which you've never seen."
    navigation = "contact"
    button = "Balloons"
    icon = "icon-wrench"
    img = "iceprincess.png"

  [[params.intro.item]]
    title = "Fairy Parties"
    description = "You won't believe how fun Pixies parties can be!"
    navigation = "services"
    button = "Fairy Parties"
    icon = "icon-rocket"
    img = "flowers.png"

  # Work section
  [params.work]
    enable = true
    title = "Gallery"
    description = "Have a look at some of Pixie's amazing faces."
    footertext = '&copy; Pixies Face Painting 2022'

    [[params.work.row]]
      img = "snowtiger.png"
      alt = "Snow Tiger"
      title = "Snow Tiger"

    [[params.work.row]]
      img = "iceprincess.png"
      alt = "Ice Princess"
      title = "Ice Princess"

    [[params.work.row]]
      img = "irridescentbutterfly.png"
      alt = "Irridescent Butterfly"
      title = "Irridescent Butterfly"

    [[params.work.row]]
      img = "snowtiger.png"
      alt = "Snow Tiger"
      title = "Snow Tiger"

    [[params.work.row]]
      img = "iceprincess.png"
      alt = "Ice Princess"
      title = "Ice Princess"

    [[params.work.row]]
      img = "irridescentbutterfly.png"
      alt = "Irridescent Butterfly"
      title = "Irridescent Butterfly"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "People love Pixie!"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Fred Bloggs'
      img = "person1.png"
      alt = "Fred Blogs"
    
  # Services section
  [params.services]
    enable = true
    title = "Booking Info"
    description = "What value for money!"

    [[params.services.item]]
      title = "Face Painting"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Ballooning"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"

    [[params.services.item]]
      title = "Fairy Parties"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "Call or send me a message"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-phone", "+61 406 074 909"],
        ["icon-facebook", "https://m.me/pixiesfaces"],
        ["icon-home", "7 Vista Avenue, Ringwood East, Victoria 3135, Australia"],
      ]

    email = "Your Email"
    phone = "Your Contact Number"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Pixies Face Painting 2022'
    links = [
        ["icon-instagram", "https://instagran.com/pixiesfaces"],
        ["icon-facebook", "https://facebook.com/pixiesfaces"],
        ["icon-twitter", "https://twitter.com/pixiesfaces"]
      ]
