[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.94.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.94.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.94.1"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.94.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-pixie = "pixie"

[[plugins]]
package = "/netlify-plugins/instagram"
  [plugins.inputs]

    # Where to put the image files
    imageFolder = "./images/instagram"

    # Where to put the instagram data file
    dataFolder = "./_data"

    # How many seconds should we cache the instagram feed for?
    feedTTL = 30

    # How many seconds should we cache each instagram image for?
    imageTTL = 1209600   # 2 weeks

[functions]
  directory = "functions"

[functions."refresh-insta-token"]
schedule = "@daily"

[dev]
functionsPort = 8888