name: netlify-plugin-add-instagram
inputs:
  - name: imageFolder
    required: true
  - name: dataFolder
    required: true
  - name: imageCount
    default: 100
  - name: feedTTL
    default: 180
  - name: imageTTL
    default: 1209600